### ISSUE TITLE
Strange problem with Nancy + Windsor + Gate

### ISSUE THREAD

**Issue by akurdyukov** [NancyFx/Nancy.Bootstrappers.Windsor#5]
Hi,

I'm trying to run Nancy app without http.sys and IIS. The example https://github.com/ArloL/NancyInGate works perfectly with TinyIoC but fails with Windsor. Steps for test:
1. Pull https://github.com/ArloL/NancyInGate project
2. Add NuGet dependency Nancy.Bootstrappers.Windsor
3. Add empty bootstrapper inherited from WindsorNancyBootstrapper
4. Run application
5. Try to access it by http://localhost:8081

After this steps I get:

```
Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Castle.MicroKernel.Lifestyle.Scoped.CallContextLifetimeScope.GetCachedInstance(ComponentModel instance, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(String key, Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Resolve(String key, Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T](String key)
   at Nancy.Bootstrappers.Windsor.WindsorNancyBootstrapper.GetModuleByKey(String moduleKey, NancyContext context)
   at Nancy.Routing.DefaultRouteResolver.GetInitializedModuleForMatch(NancyContext context, Tuple`4 routeMatchToReturn)
   at Nancy.Routing.DefaultRouteResolver.CreateRouteAndParametersFromMatch(NancyContext context, Tuple`4 routeMatchToReturn)
   at Nancy.Routing.DefaultRouteResolver.Resolve(String path, NancyContext context, IRouteCache routeCache)
   at Nancy.Routing.DefaultRouteResolver.Resolve(NancyContext context)
   at Nancy.NancyEngine.ResolveAndInvokeRoute(NancyContext context)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, IPipelines pipelines)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

My brief examination shows that there's problem with private cache in CallContextLifetimeScope instance. On first call for WindsorNancyBootstrapper.GetModuleByKey object of type CallContextLifetimeScope exists and returns with CallContextLifetimeScope.ObtainCurrentScope(). But it seems to be disposed - cache is null already.

**Comment by Grinderofl** [comment]
I'm letting you guys know that this is still an actual issue.Nancy + Windsor + owin self host + async = scope gets disposed before the request ends, so awaiting after some EF6 queries fails with disposed objectcontext.

I've solved it for our project in a similar fashion by LifestyleScoped() everything that has to be per request and adding it into the context inside a similar wrapper, rather than nearest INancyModule. It seems to work so all good.
