### ISSUE TITLE
Castle.MicroKernel.Lifestyle.WebRequestScopeAccessor

### ISSUE THREAD

**Issue by tasoss** [NancyFx/Nancy.Bootstrappers.Windsor#57]
Hello.
I have just updated a solution with a few projects.
And i get the following error.

>    at Nancy.Bootstrappers.Windsor.NancyPerWebRequestScopeAccessor..ctor()
   at lambda_method(Closure , Object[] )
   at Castle.Core.Internal.ReflectionUtil.Instantiate(ConstructorInfo ctor, Object[] ctorArgs)
   at Castle.Core.Internal.ReflectionUtil.Instantiate[TBase](Type subtypeofTBase, Object[] ctorArgs)
   at Castle.Core.Internal.ReflectionUtil.CreateInstance[TBase](Type subtypeofTBase, Object[] ctorArgs)
   at Castle.MicroKernel.DefaultKernel.CreateScopeAccessor(ComponentModel model)
   at Castle.MicroKernel.DefaultKernel.CreateLifestyleManager(ComponentModel model, IComponentActivator activator)
   at Castle.MicroKernel.Handlers.DefaultHandler.InitDependencies()
   at Castle.MicroKernel.Handlers.AbstractHandler.Init(IKernelInternal kernel)
   at Castle.MicroKernel.Handlers.DefaultHandlerFactory.Create(ComponentModel model)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.CreateHandler(ComponentModel model)
   at Castle.MicroKernel.DefaultKernel.AddCustomComponent(ComponentModel model)
   at Castle.MicroKernel.Registration.ComponentRegistration`1.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations)
   at Castle.Windsor.WindsorContainer.Register(IRegistration[] registrations)
   at Nancy.Bootstrappers.Windsor.WindsorNancyBootstrapper.RegisterModules(IWindsorContainer container, IEnumerable`1 moduleRegistrationTypes)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
   at Owin.AppBuilderExtensions.UseNancy(IAppBuilder builder, NancyOptions options)
   at DatabaseRest.Startup.Configuration(IAppBuilder app) in C:\foobar\Startup.cs:line 83
   
   
   Could not load type 'Castle.MicroKernel.Lifestyle.WebRequestScopeAccessor' from assembly 'Castle.Windsor, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'.
   

> 

I'm using castle.windsor v5 and Nancy.Bootstrappers.Windsor 1.4.1 (i have tried v2 too)
Am i doing something wrong?
Thanks!

**Comment by robsonj** [comment]
We see the same issue, we had to move back to Castle.Windsor 4.1.1

**Comment by waynebx** [comment]
I had the same issue. Turned out it was a third party library that I was using that caused this (in my case it was the deprecated Castle.Windsor.Lifestyles because I wanted to use the Hybrid lifestyles). If that's also your case, you can fork the library, correct the dependencies and use the forked one in your code.

**Comment by robsonj** [comment]
Added Pull #58 to address this. May need some assistance to get it working with Cake. But would really like to get a new v2.0.0 of this package out there if possible please.

https://github.com/NancyFx/Nancy.Bootstrappers.Windsor/pull/58

**Comment by tasoss** [comment]
Hello again.
I have tried to use the 2.0.0 version of nancy(during the process of updating nuget packages) and i get the same error.
Is it supposed to have been fixed?
Sorry i'm just confused.

**Comment by tasoss** [comment]
Finally i have used your repo and everything is fine.
But why isn't it yet merged ?
Thanks!

**Comment by robsonj** [comment]
I gave up trying to get help to merge it. In the end I pulled the few classes into our repo with a plan to migrate away from NancyFx

**Comment by tasoss** [comment]
I agree!
Thanks again!
